sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t an071093/docker-react  -f Dockerfile.dev .

script: 
  - docker run -e CI=true an071093/docker-react npm run test